spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/food
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

# api 조회시 필요한 정보들(외부에 노출되서는 안되거나 변하지 않는값들)
openApi:
  baseUrl: http://apis.data.go.kr/1471000/FoodNtrIrdntInfoService1/getFoodNtrItdntList1?
  ServiceKey: RRAZ7WfqxV7iXm8KE6cMuImCqAiHG/n1fVI6E/bnzlmWxRNU1l/EsHQ8794sz47WFNlM1HMaQCv8/tWAH2gBqQ==
  type: json